{{- if .Values.ingress.enabled -}}
{{- $fullName := include "dqhi.fullname" . -}}
{{- $servicePort := .Values.service.port -}}
{{- $ingressPath := include "dqhi.ingress" . -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    app: {{ template "dqhi.name" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
{{- with .Values.ingress.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
spec:
  rules:
    - http:
          paths:
          - path: {{ $ingressPath }}
            backend:
              serviceName: {{ $fullName }}
              servicePort: {{ printf "%.0f" $servicePort }}
{{- end }}
