apiVersion: v1
kind: ConfigMap
metadata:
    labels:
        app: {{ template "dqhi.fullname" . }}
        release: {{ .Release.Name }}
        heritage: {{ .Release.Service }}
    name: {{ template "dqhi.fullname" . }}-settings
    namespace: {{ .Release.Namespace }}
data:
    MAX_START_DATE_RANGE: "7"
    DATA_RETENTION_IN_DAYS: "14"
    SPARK_CONFIG: "--conf spark.dynamicAllocation.enabled=true --conf spark.shuffle.service.enabled=true --conf spark.sql.crossJoin.enabled=true --conf spark.sql.execution.arrow.enabled=true --conf spark.sql.parquet.compression.codec=snappy --conf spark.ui.port=4041 --conf spark.sql.broadcastTimeout=14400 --conf spark.executorEnv.FILE_READER=com.nsn.ngdb.common.hive.io.reader.ParquetFileReader --conf spark.yarn.appMasterEnv.FILE_READER=com.nsn.ngdb.common.hive.io.reader.ParquetFileReader --conf spark.sql.parquet.writeLegacyFormat=true --conf spark.yarn.appMasterEnv.Xms=-Xms64m --conf spark.yarn.appMasterEnv.Xmx=-Xmx64m --conf spark.yarn.appMasterEnv.STATIC_PARTITION_SIZE=134217728 --conf spark.yarn.appMasterEnv.DYNAMIC_RECORD_COUNT=3000000 --conf spark.eventLog.enabled=true --conf spark.eventLog.dir=hdfs://namenodeHA/user/spark/spark2ApplicationHistory --conf spark.yarn.historyServer.address=http://cdlk-control-01.rijin.com:18089 --conf spark.yarn.appMasterEnv.HIVESCHEMA=project --conf spark.yarn.queue=root.rijin.ca4ci.DQI"