apiVersion: apps/v1
kind: Deployment
metadata:
    name: simple-rest-api-deployment
    labels:
        app: demo-deployment
spec:
    replicas: 1
    selector:
        matchLabels:
            app: demo-deployment
    template:
        metadata:
            labels:
                app: demo-deployment
        spec:
            containers:
                - name: myhttpd1
                  image: simple-rest-api
                  imagePullPolicy: Never
                  ports:
                    - name: http
                      containerPort: 80
                      protocol: TCP