apiVersion: v1
kind: Service
metadata:
    name: demo-service
spec:
    type: NodePort
    selector:
        app: demo-deployment
    ports:
          - port: 80
            targetPort: 8080
            name: http
