EXCEL_PATH = r'C:\Users\rithomas\AppData\Roaming\Microsoft\Excel'
MARIADB_URL = 'mysql+mysqlconnector://root:zaq12wsx@127.0.0.1/testrijdb'
TABLE_PATTERN = ['US_SMS', 'CP_SEGG']
PATTERN_CONSTRUCTOR = ''
CONDITION_CONSTRUCTOR = 'and ({})'
PORT = 465  # For SSL
SMTP_SERVER = "smtp.gmail.com"
SENDER_EMAIL = "thomasct2253@gmail.com"  # Enter your address
RECEIVER_EMAIL = "rijinct@gmail.com"  # Enter receiver address
PASSWORD = 'aeazjueefupjarav'
MESSAGE = """Subject: Alert:Threshold reached for {}"""