import pandas as pd

mns_dict = {
    'field_name': ['ORIGINS Pregnancy Number', 'Maternal ORIGINS Unique ID',
                   'Child ORIGINS Unique ID', 'Child MN Number', 'child_order',
                   'Morbidity Record Type', 'Feeder Identifer',
                   'Record Linking Identifier', 'BIR Establishment',
                   'Mother MN Number', 'BIR Event Date', 'BIR Event Time',
                   'BIR Plurality', 'Birth Order', 'Adoption Indicator',
                   'Born Before Arrival Indicator', 'Presentation',
                   'Method of Birth', 'Accoucheurs', 'Gender',
                   'Status of the Baby', 'Infant Weight', 'Length',
                   'Head Circumference',
                   'Time to establish unassisted regular breathing',
                   'Resuscitation', 'Apgar Score - 1 Minute',
                   'Apgar Score - 5 Minutes', 'Estimated Gestation',
                   'Birth Defects', 'Birth Trauma ICD1', 'Birth Trauma ICD2',
                   'Birth Trauma ICD3', 'Birth Trauma ICD4',
                   'Birth Trauma ICD5', 'Event End Date', 'Event End Time',
                   'Mode of Separation', 'Separated/Transferred To',
                   'Special Care Days', 'Anaesthesia',
                   'Complications of Labour and Birth',
                   'Complications of Labour and Delivery ICD1',
                   'Complications of Labour and Delivery ICD2',
                   'Complications of Labour and Delivery ICD3',
                   'Complications of Labour and Delivery ICD4',
                   'Complications of Labour and Delivery ICD5',
                   'Perineal Status', 'Indigenous Status of Baby',
                   'Principal Reason for Caesarean Section',
                   'Water immersion at Birth', 'DEL Establishment',
                   'DEL Event Date', 'DEL Event Time', 'Surname',
                   'First Forename', 'Second Forename', 'Maiden Name',
                   'Residential Address', 'Suburb', 'Postcode',
                   'State/Territory of Residence', 'Locality', 'Date of Birth',
                   'Height', 'Telephone Number', 'Location', 'Marital Status',
                   'Ethnic Origin', 'Previous Pregnancies', 'Children Living',
                   'Children Died', 'Stillbirths',
                   'Previous Caesarean Indicator', 'Caesarean Last Delivery',
                   'Previous Multiple Birth Indicator',
                   'Estimated gestation weeks at first antenatal visit',
                   'Total Number of antenatal visits', 'Date LMP',
                   'Date LMP Certain', 'Expected Due Date',
                   'Basis Expected Due Date',
                   'Smoking During Pregnancy Indicator',
                   'Number of tobacco cigarettes usually smoked each day during FIRST 20 weeks of pregnancy',
                   'Number of cigarettes usually smoked each day AFTER 20 weeks of pregnancy',
                   'Complications of Pregnancy',
                   'Complications of Pregnancy ICD1',
                   'Complications of Pregnancy ICD2',
                   'Complications of Pregnancy ICD3',
                   'Complications of Pregnancy ICD4',
                   'Complications of Pregnancy ICD5', 'Medical Conditions',
                   'Medical Conditions ICD1', 'Medical Conditions ICD2',
                   'Medical Conditions ICD3', 'Medical Conditions ICD4',
                   'Medical Conditions ICD5', 'Procedures & Treatments',
                   'Intended Place of Birth', 'Onset of Labour',
                   'Type of Augmentation', 'Type of Induction', 'Analgesia',
                   'DEL Plurality', 'Duration of Labour - 1st Stage',
                   'Duration of Labour - 2nd Stage', 'Midwife Name',
                   'Midwife Registration Number', 'Coder Indentifier',
                   'Mothers Weight', 'Number of Previous Caesareans',
                   'Previous Pregnancies - Parity',
                   'Postnatal blood loss in mls',
                   'Interpreter service required',
                   'Mother\'s language requiring interpreter',
                   'Influenza vaccination during pregnancy',
                   'Pertussis vaccination during pregnancy',
                   'Principal reason for induction of labour',
                   'During pregnancy, was screening for family violence conducted',
                   'Primary maternity model of care',
                   'Maternity model of care at onste of labour or non-labour caesarean',
                   'Specification', 'Source',
                   'Complications of Labour and Delivery',
                   'First 20 weeks of pregnancy, the frequency of drinking an alcoholic drink',
                   'First 20 weeks of pregnancy, the number of standard drinks containing alcohol on a typical day when alcohol is consumed',
                   'During pregnancy, was screening for depression / anxiety conducted',
                   'Was additional follow-up indicated for perinatal mental health risk factors identified',
                   'During 3rd Trimester, was screening for depression / anxiety conducted',
                   'From 3rd Trimester was additional follow-up indicated for perinatal mental health risk factors identified',
                   'Email',
                   'After 20 weeks of pregnancy, the frequency of drinking an alcoholic drink',
                   'After 20 weeks of pregnancy, the number of standard drinks containing alcohol on a typical day when alcohol is consumed']}
df = pd.DataFrame(mns_dict)

print(df)
