tags:
  - Operational Metadata Configuration
summary: Configure job list
parameters:
  - in: body
    name: configParamList
    multiLine: true
    description: Pass configuration parameters for operational metadata.
    required: true
    multiLine: true
    schema:
      type: array
    example: Usage_SMS_1_LoadJob,Perf_VOICE_SEGG_1_HOUR_AggregateJob
responses:
  200:
    description: "Success"
  400:
    description: "Bad Request"
  500:
    description: ERROR Failed!