tags:
  - Operational Metadata Configuration
summary: Get the configured jobs
responses:
  200:
    description: "Success"
  400:
    description: "Bad Request"
  500:
    description: ERROR Failed!