tags:
  - Technical Metadata Configuration
summary: Configure table list
parameters:
  - in: body
    name: configParamList
    multiLine: true
    description: Pass configuration parameters for technical metadata.
    required: true
    multiLine: true
    schema:
      type: array
    example: US%,PS_SMS_SEGG%
responses:
  200:
    description: "Success"
  400:
    description: "Bad Request"
  500:
    description: ERROR Failed!