'''
Created on 22-Aug-2020

@author: rithomas
'''
nifty50 =               ['ADANIPORTS'  ,
                        'ASIANPAINT'  ,
                        'AXISBANK'    ,
                        'BAJAJ-AUTO'  ,
                        'BAJFINANCE'  ,
                        'BAJAJFINSV'  ,
                        'BPCL'        ,
                        'BHARTIARTL'  ,
                        'INFRATEL'    ,
                        'CIPLA'       ,
                        'COALINDIA'   ,
                        'DRREDDY'     ,
                        'EICHERMOT'   ,
                        'GAIL'        ,
                        'GRASIM'      ,
                        'HCLTECH'     ,
                        'HDFCBANK'    ,
                        'HEROMOTOCO'  ,
                        'HINDALCO'    ,
                        'HINDPETRO'   ,
                        'HINDUNILVR'  ,
                        'HDFC'        ,
                        'ITC'         ,
                        'ICICIBANK'   ,
                        'IBULHSGFIN'  ,
                        'IOC'         ,
                        'INDUSINDBK'  ,
                        'INFY'        ,
                        'JSWSTEEL'    ,
                        'KOTAKBANK'   ,
                        'LT'          ,
                        'M&M'         ,
                        'MARUTI'      ,
                        'NTPC'        ,
                        'ONGC'        ,
                        'POWERGRID'   ,
                        'RELIANCE'    ,
                        'SBIN'        ,
                        'SUNPHARMA'   ,
                        'TCS'         ,
                        'TATAMOTORS'  ,
                        'TATASTEEL'   ,
                        'TECHM'       ,
                        'TITAN'       ,
                        'UPL'         ,
                        'ULTRACEMCO'  ,
                        'VEDL'        ,
                        'WIPRO'       ,
                        'YESBANK'     ,
                        'ZEEL' ]

st_non_nifty = ['APOLLOTYRE'  ,
                    'DABUR'       ,
                    'PETRONET'    ,
                    'TORNTPOWER'  ,
                    'MARICO'      ,
                    'AMBUJACEM'   ,
                    'HAVELLS'     ,
                    'SUNTV'       ,
                    'TVSMOTOR'    ,
                    'VOLTAS'      ,
                    'CADILAHC'    ,
                    'TATACHEM'    ,
                    'BATAINDIA'   ,
                    'BIOCON'      ,
                    'CENTURYTEX'  ,
                    'LICHSGFIN'   ,
                    'NIITTECH'    ,
                    'PIDILITIND'  ,
                    'IBULHSGFIN'  ,
                    'KOTAKBANK'   ,
                    'MINDTREE'    ,
                    'AUROPHARMA'  ,
                    'GLENMARK'    ,
                    'AMARAJABAT'  ,
                    'BHARATFORG'  ,
                    'CUMMINDIND'  ,
                    'DIVISLAB'    ,
                    'SRTRANSFIN'  ,
                    'CONCOR'      ,
                    'JUBLFOOD'    ,
                    'SIEMENS'     ,
                    'SRF'         ,
                    'ACC'         ,
                    'APOLLOHOSP'  ,
                    'GODREJCP'    ,
                    'LUPIN'       ,
                    'MCDOWELL-N'  ,
                    'BRITANNIA'   ,
                    'DRREDDY'     ,
                    'BOSCHLTD'    ,
                    'PAGEIND'     ,
                    'MRF']

a_set = set(nifty50)
b_set = set(st_non_nifty)

if (a_set & b_set): 
        print(a_set & b_set) 
else: 
        print("No common elements")  