'''
Created on 25-Apr-2020

@author: rithomas
'''

MARIADB_URL = 'mysql+mysqlconnector://root:zaq12wsx@127.0.0.1/testrijdb'

vwap_sql_query_5 = '''
select trading_symbol, total_cumVolumeLtp, total_traded_vol, total_cumVolumeLtp/total_traded_vol as vwap from (select trading_symbol,\
SUM(totalTradedVolume) as total_traded_vol, SUM(cumVol_X_Ltp) as total_cumVolumeLtp from st_nse_data_5 \
    where STR_TO_DATE(lastUpdateTime, '%d-%M-%Y') = '{todays_date}' group by trading_symbol)q1'''
    
vwap_sql_query_Pi = '''
select Trading_symbol, total_cumVolumeLtp, total_traded_vol, total_cumVolumeLtp/total_traded_vol as vwap from (select
Trading_symbol,SUM(volume_traded_today) AS total_traded_vol, SUM(cumVol_X_Ltp) as total_cumVolumeLtp from (select
Trading_symbol,volume_traded_today,ATP*Volume_traded_today as cumVol_X_Ltp from st_analysis_5 where 
STR_TO_DATE(LTT, '%d-%m-%Y') = '{todays_date}')q group by Trading_symbol)r
'''

xlsb_column_list = ['Trading_symbol', 'LTP', 'Bid_qty', 'Bid_rate', 'Ask_rate', 'Ask_qty', 'LTQ', 'Open', 'High', 'Low', 'Prev_close', 'Volume_traded_today', 'Open_interest', 'ATP', 'Total_bid_qty', 'Total_ask_qty', 'Exchange', 'LTT', 'LUT']

nsePy_minData_col = ['tradedDate', 
                        'data_0_pricebandupper', 
                       'data_0_symbol',
                       'data_0_applicableMargin', 
                       'data_0_bcEndDate',
                       'data_0_totalSellQuantity', 
                       'data_0_adhocMargin', 
                       'data_0_companyName',
                       'data_0_marketType', 
                       'data_0_exDate',
                        'data_0_bcStartDate',
                       'data_0_css_status_desc', 
                       'data_0_dayHigh', 
                       'data_0_basePrice',
                       'data_0_securityVar', 
                       'data_0_pricebandlower', 
                       'data_0_sellQuantity5',
                       'data_0_sellQuantity4', 
                       'data_0_sellQuantity3', 
                       'data_0_cm_adj_high_dt',
                       'data_0_sellQuantity2', 
                       'data_0_dayLow', 
                       'data_0_sellQuantity1',
                       'data_0_quantityTraded', 
                       'data_0_pChange', 
                       'data_0_totalTradedValue',
                       'data_0_deliveryToTradedQuantity', 
                       'data_0_totalBuyQuantity',
                       'data_0_averagePrice', 
                       'data_0_indexVar', 
                       'data_0_cm_ffm',
                       'data_0_purpose', 
                       'data_0_buyPrice2', 
                       'data_0_secDate',
                       'data_0_buyPrice1', 
                       'data_0_high52', 
                       'data_0_previousClose',
                       'data_0_ndEndDate', 
                       'data_0_low52', 
                       'data_0_buyPrice4',
                       'data_0_buyPrice3', 
                       'data_0_recordDate', 
                       'data_0_deliveryQuantity',
                       'data_0_buyPrice5', 
                       'data_0_priceBand', 
                       'data_0_extremeLossMargin',
                       'data_0_cm_adj_low_dt', 
                       'data_0_varMargin', 
                       'data_0_sellPrice1',
                       'data_0_sellPrice2', 
                       'data_0_totalTradedVolume', 
                       'data_0_sellPrice3',
                       'data_0_sellPrice4', 
                       'data_0_sellPrice5', 
                       'data_0_change',
                       'data_0_surv_indicator', 
                       'data_0_ndStartDate', 
                       'data_0_buyQuantity4',
                       'data_0_isExDateFlag', 
                       'data_0_buyQuantity3', 
                       'data_0_buyQuantity2',
                       'data_0_buyQuantity1', 
                       'data_0_series', 
                       'data_0_faceValue',
                       'data_0_buyQuantity5', 
                       'data_0_closePrice', 
                       'data_0_open',
                       'data_0_isinCode', 
                       'data_0_lastPrice', 
                       'optLink',
                       'lastUpdateTime']

nse_data_act_col= ['tradedDate', 
                       'data_0_symbol',
                       'data_0_totalSellQuantity', 
                       'data_0_companyName',
                       'data_0_marketType', 
                       'data_0_dayHigh', 
                       'data_0_basePrice',
                       'data_0_securityVar',  
                       'data_0_dayLow', 
                       'data_0_quantityTraded', 
                       'data_0_pChange', 
                       'data_0_totalTradedValue',
                       'data_0_totalBuyQuantity',
                       'data_0_averagePrice', 
                       'data_0_purpose',  
                       'data_0_high52', 
                       'data_0_previousClose',
                       'data_0_low52',  
                       'data_0_totalTradedVolume', 
                       'data_0_change',
                       'data_0_surv_indicator',                       
                       'data_0_closePrice', 
                       'data_0_open',
                       'data_0_lastPrice', 
                       'lastUpdateTime']

nse_data_col= ['tradedDate', 
                       'symbol',
                       'totalSellQuantity', 
                       'companyName',
                       'marketType', 
                       'dayHigh', 
                       'basePrice',
                       'securityVar',  
                       'dayLow', 
                       'quantityTraded', 
                       'pChange', 
                       'totalTradedValue',
                       'totalBuyQuantity',
                       'averagePrice', 
                       'purpose',  
                       'high52', 
                       'previousClose',
                       'low52',  
                       'totalTradedVolume', 
                       'changePrice',
                       'surv_indicator',                       
                       'closePrice', 
                       'openPrice',
                       'lastPrice', 
                       'lastUpdateTime']


nse_data_with_ta = ['tradedDate', 
                       'trading_symbol',
                       'totalSellQuantity', 
                       'companyName',
                       'marketType', 
                       'dayHigh', 
                       'basePrice',
                       'securityVar',  
                       'dayLow', 
                       'quantityTraded', 
                       'pChange', 
                       'totalTradedValue',
                       'totalBuyQuantity',
                       'averagePrice', 
                       'purpose',  
                       'high52', 
                       'previousClose',
                       'low52',  
                       'totalTradedVolume', 
                       'changePrice',
                       'surv_indicator',                       
                       'closePrice', 
                       'openPrice',
                       'lastPrice', 
                       'lastUpdateTime',
                       'vwap',
                       'macd',
                       'macdsignal',
                       'macdhist']

pi_data_with_ta = ['Trading_symbol', 
                         'LTP', 
                         'Bid_qty', 
                         'Bid_rate',
                         'Ask_rate',
                         'Ask_qty', 
                         'LTQ', 
                         'Open', 
                         'High', 
                         'Low', 
                         'Prev_close', 
                         'Volume_traded_today',
                         'Open_interest', 
                         'ATP', 
                         'Total_bid_qty', 
                         'Total_ask_qty', 
                         'Exchange',
                         'LTT', 
                         'LUT', 
                         'cumVol_X_Ltp', 
                         'vwap',
                         'vwap_ltp_diff', 
                         'macd', 
                         'macdsignal', 
                         'macdhist']

pi_data_with_ta_ST = ['Trading_symbol', 
                         'LTP', 
                         'Bid_qty', 
                         'Bid_rate',
                         'Ask_rate',
                         'Ask_qty', 
                         'LTQ', 
                         'Open', 
                         'High', 
                         'Low', 
                         'Prev_close', 
                         'Volume_traded_today',
                         'Open_interest', 
                         'ATP', 
                         'Total_bid_qty', 
                         'Total_ask_qty', 
                         'Exchange',
                         'LTT', 
                         'LUT', 
                         'cumVol_X_Ltp', 
                         'vwap',
                         'vwap_ltp_diff', 
                         'macd', 
                         'macdsignal', 
                         'macdhist',
                         'st_7_2',
                         'st_7_3',
                         'st_10_4']

nifty50 =               ['ADANIPORTS'  ,
                        'ASIANPAINT'  ,
                        'AXISBANK'    ,
                        'BAJAJ-AUTO'  ,
                        'BAJFINANCE'  ,
                        'BAJAJFINSV'  ,
                        'BPCL'        ,
                        'BHARTIARTL'  ,
                        'INFRATEL'    ,
                        'CIPLA'       ,
                        'COALINDIA'   ,
                        'DRREDDY'     ,
                        'EICHERMOT'   ,
                        'GAIL'        ,
                        'GRASIM'      ,
                        'HCLTECH'     ,
                        'HDFCBANK'    ,
                        'HEROMOTOCO'  ,
                        'HINDALCO'    ,
                        'HINDPETRO'   ,
                        'HINDUNILVR'  ,
                        'HDFC'        ,
                        'ITC'         ,
                        'ICICIBANK'   ,
                        'IBULHSGFIN'  ,
                        'IOC'         ,
                        'INDUSINDBK'  ,
                        'INFY'        ,
                        'JSWSTEEL'    ,
                        'KOTAKBANK'   ,
                        'LT'          ,
                        'M&M'         ,
                        'MARUTI'      ,
                        'NTPC'        ,
                        'ONGC'        ,
                        'POWERGRID'   ,
                        'RELIANCE'    ,
                        'SBIN'        ,
                        'SUNPHARMA'   ,
                        'TCS'         ,
                        'TATAMOTORS'  ,
                        'TATASTEEL'   ,
                        'TECHM'       ,
                        'TITAN'       ,
                        'UPL'         ,
                        'ULTRACEMCO'  ,
                        'VEDL'        ,
                        'WIPRO'       ,
                        'YESBANK'     ,
                        'ZEEL' ]

st_non_nifty = ['apollotyre'  ,
                    'dabur'       ,
                    'petronet'    ,
                    'torntpower'  ,
                    'marico'      ,
                    'ambujacem'   ,
                    'havells'     ,
                    'suntv'       ,
                    'tvsmotor'    ,
                    'voltas'      ,
                    'cadilahc'    ,
                    'tatachem'    ,
                    'bataindia'   ,
                    'biocon'      ,
                    'centurytex'  ,
                    'lichsgfin'   ,
                    'niittech'    ,
                    'pidilitind'  ,
                    'mindtree'    ,
                    'auropharma'  ,
                    'glenmark'    ,
                    'amarajabat'  ,
                    'bharatforg'  ,
                    'cummindind'  ,
                    'divislab'    ,
                    'srtransfin'  ,
                    'concor'      ,
                    'jublfood'    ,
                    'siemens'     ,
                    'srf'         ,
                    'acc'         ,
                    'apollohosp'  ,
                    'godrejcp'    ,
                    'lupin'       ,
                    'britannia'   ,
                    'boschltd'    ,
                    'pageind'     ,
                    'mrf'         ,
                    'dlf']

non_nifty_wrk = ['ACC',
                    'AMARAJABAT',
                    'AMBUJACEM',
                    'APOLLOHOSP',
                    'APOLLOTYRE',
                    'AUROPHARMA',
                    'BATAINDIA',
                    'BHARATFORG',
                    'BIOCON',
                    'BOSCHLTD',
                    'BRITANNIA',
                    'GLENMARK',
                    'HAVELLS',
                    'JUBLFOOD',
                    'LUPIN',
                    'MARICO',
                    'MRF',
                    'NIITTECH',
                    'PAGEIND',
                    'PETRONET',
                    'SIEMENS',
                    'SRF',
                    'SRTRANSFIN',
                    'SUNTV',
                    'TORNTPOWER',
                    'TVSMOTOR']


st_numeric_cols = ['LTP', 
                   'Bid_qty',
                   'Bid_rate',  
                   'Ask_rate',
                   'Ask_qty', 
                   'LTQ', 
                   'Open', 
                   'High', 
                   'Low', 
                   'Prev_close', 
                   'Volume_traded_today',
                   'Open_interest', 
                   'ATP', 
                   'Total_bid_qty', 
                   'Total_ask_qty',  
                   'cumVol_X_Ltp', 
                   'vwap', 
                   'vwap_ltp_diff', 
                   'macd',
                   'macdsignal', 
                   'macdhist']

st_day_numeric_cols = ['macd_day',
                   'macdsignal_day', 
                   'macdhist_day']
    
st_xlsb_numeric_cols = ['LTP', 
                   'Bid_qty',
                   'Bid_rate',  
                   'Ask_rate',
                   'Ask_qty', 
                   'LTQ', 
                   'Open', 
                   'High', 
                   'Low', 
                   'Prev_close', 
                   'Volume_traded_today',
                   'Open_interest', 
                   'ATP', 
                   'Total_bid_qty', 
                   'Total_ask_qty',  
                   'cumVol_X_Ltp']

non_nifty_test = ['ACC',
                    'AMARAJABAT',
                    'AMBUJACEM',
                    'APOLLOHOSP',
                    'APOLLOTYRE',
                    'NIITTECH']

st_dayDf_col_list = ['Trading_symbol', 
                    'Series', 
                    'Prev Close', 
                    'Open', 
                    'High', 
                    'Low', 
                    'Last',     
                    'LTP', 
                    'VWAP', 
                    'Volume', 
                    'Turnover', 
                    'Trades', 
                    'Deliverable Volume',
                    '%Deliverble']

st_aler_num_col = ['LTP', 'vwap', 'macd','macdsignal','macdhist','st_7_2','st_7_3','st_10_4','macd_day','macdsignal_day','macdhist_day','st_7_2_day','st_7_3_day']


st_dayDf_final_col_list = ['Trading_symbol', 
                            'Series', 
                            'Prev Close', 
                            'Open', 
                            'High', 
                            'Low', 
                            'Last',
                            'LTP', 
                            'VWAP', 
                            'macd_day', 
                            'macdsignal_day', 
                            'macdhist_day', 
                            'st_7_2_day', 
                            'st_7_3_day']

st_analysis_5minQuery = '''
SELECT Trading_symbol,LTP,Bid_qty,Bid_rate,Ask_rate,Ask_qty,LTQ,Open,High,Low,Prev_close,Volume_traded_today,Open_interest,ATP,Total_bid_qty,Total_ask_qty,Exchange,LTT,LUT,
cumVol_X_Ltp,LTT_5MIN FROM (select Trading_symbol,LAST_VALUE(LTP) over(PARTITION BY Trading_symbol) AS LTP,Bid_qty,Bid_rate,Ask_rate,Ask_qty,LTQ,LAST_VALUE(OPEN) 
over(PARTITION BY Trading_symbol) AS OPEN,
LAST_VALUE(High) over(PARTITION BY Trading_symbol) AS High,LAST_VALUE(Low) over(PARTITION BY Trading_symbol) AS Low,LAST_VALUE(Prev_close) over(PARTITION BY Trading_symbol) AS 
Prev_close,LAST_VALUE(Volume_traded_today) over(PARTITION BY Trading_symbol) AS Volume_traded_today,Open_interest,LAST_VALUE(ATP) over(PARTITION BY Trading_symbol) AS ATP,
Total_bid_qty,Total_ask_qty,EXCHANGE,LAST_VALUE(LTT) over(PARTITION BY Trading_symbol) AS LTT,LAST_VALUE(LUT) over(PARTITION BY Trading_symbol) AS LUT,cumVol_X_Ltp,
LAST_VALUE(LTT_5MIN) over(PARTITION BY Trading_symbol) AS LTT_5MIN FROM 
(SELECT Trading_symbol,LAST_VALUE(LTP) over(PARTITION BY Trading_symbol,LTT_5MIN) AS LTP,Bid_qty,Bid_rate,Ask_rate,Ask_qty,LTQ,FIRST_VALUE(LTP) 
over(PARTITION BY Trading_symbol,LTT_5MIN) AS Open,MAX(LTP) over(PARTITION BY Trading_symbol,LTT_5MIN) AS High,MIN(LTP) over(PARTITION BY Trading_symbol,LTT_5MIN) AS Low,
Prev_close,LAST_VALUE(Volume_traded_today) over(PARTITION BY Trading_symbol,LTT_5MIN) AS Volume_traded_today,Open_interest,LAST_VALUE(ATP) over(PARTITION BY Trading_symbol,
LTT_5MIN) AS ATP,Total_bid_qty,Total_ask_qty,Exchange,LAST_VALUE(LTT) over(PARTITION BY Trading_symbol,LTT_5MIN) AS LTT,LUT,LAST_VALUE(cumVol_X_Ltp) 
over(PARTITION BY Trading_symbol,LTT_5MIN) AS cumVol_X_Ltp,LTT_5MIN from 
(SELECT Trading_symbol,LTP,Bid_qty,Bid_rate,Ask_rate,Ask_qty,LTQ,Open,High,Low,Prev_close,Volume_traded_today,Open_interest,ATP,Total_bid_qty,
Total_ask_qty,Exchange,LTT,LUT,cumVol_X_Ltp,from_unixtime(ceiling(UNIX_TIMESTAMP(STR_TO_DATE(LTT, '%d-%m-%Y %H:%i:%s'))/300)*300) 
AS LTT_5MIN FROM st_analysis WHERE  STR_TO_DATE(LTT, '%d-%m-%Y') > '{d}' ORDER BY
STR_TO_DATE(LTT, '%d-%m-%Y %H:%i:%s') desc)q)r)s GROUP BY trading_symbol'''


st_macd_superT_query = '''
SELECT * FROM st_analysis_5 WHERE Trading_symbol LIKE '{s}' and STR_TO_DATE(LTT, '%d-%m-%Y') > '{d}' ORDER BY STR_TO_DATE(LTT, '%d-%m-%Y %H:%i:%s') ASC
'''

st_analysis_nifty50_dayQuery = '''
SELECT Trading_symbol,macd_day,macdsignal_day,macdhist_day,st_7_2_day,st_7_3_day FROM  st_analysis_nifty50_day
'''
delete_query_st_analysis = '''
    DELETE from testrijdb.st_analysis where STR_TO_DATE(LTT, '%d-%m-%Y') < '{}'
    '''

delete_query_st_analysis_5= '''
    DELETE from testrijdb.st_analysis_5 where STR_TO_DATE(LTT, '%d-%m-%Y') < '{}'
    '''


