cdlk:
  enabled: true
  tls:
    enabled: true
    cert_path: /usr/lib/jvm/java-1.8.0-openjdk-1.8.0.242.b08-0.el7_7.x86_64/jre/lib/security/
    secret_name: ca4ci-jsscert-secrets

etlconfigservice:
  name: etlconfigservice
  port: 8080

cacheserviceagent:
  name: cacheserviceagent
  port: 8080
  readtimeout: 180

dimensionfilevalidator:
  name: dimensionfilevalidator
  port: 8080

queryschedulerservice:
  name: queryscheduler
  port: 8080
  readtimeout: 60
  
exportservice:
  name: exportservice
  port: 8080

  os_user: "rithomas"
    port: 8443
  namespace: "paas"
  realm: "ap-core"
  clientId: "ca4ci"
  userRole: "PORTAL_ADMIN"
  token: "Bearer eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJ2TEI2U1N3aVdJd3F6SEJHSFQ0MVd1V3lmOXREOFpFZGtlcjRPTlVmSHhNIn0.eyJqdGkiOiI4ZjhmYjI1OS02MjE4LTQ0NTQtYWIzOS1hODY5YzEwMjcwZjciLCJleHAiOjE1NDQ2NDk1ODIsIm5iZiI6MCwiaWF0IjoxNTQ0NjEzNTgyLCJpc3MiOiJodHRwczovL2F1dGgtbjA0LWcwMy1lLTAxL2F1dGgvcmVhbG1zL0FQQUFTIiwiYXVkIjoiQ0E0Q0kiLCJzdWIiOiI1NzhhMmQ0NS1kMDJkLTQ5ZGItYWQ0Yy1kOGJjMDgwYTZlMGIiLCJ0eXAiOiJCZWFyZXIiLCJhenAiOiJDQTRDSSIsImF1dGhfdGltZSI6MCwic2Vzc2lvbl9zdGF0ZSI6IjBhYmU4ZmExLWFlMzctNDE2NC04YzBmLTQzY2IyZDFiZGQyNiIsImFjciI6IjEiLCJhbGxvd2VkLW9yaWdpbnMiOltdLCJyZXNvdXJjZV9hY2Nlc3MiOnsiQ0E0Q0kiOnsicm9sZXMiOlsiQU5BTFlUSUNTX1VTRVIiLCJDRUlfVVNFUiIsIkZMX1VTRVIiLCJDUUlfVVNFUiIsIkFVVE9fUkVGUkVTSCIsIkwxIiwiTDIiLCJFWFBPUlQiLCJQSUlfVU5NQVNLSU5HIiwiUE9SVEFMX0FETUlOIiwiQ0NUX0RFU0lHTkVSIl19fSwibmFtZSI6IlBvcnRhbCBBZG1pbiIsInByZWZlcnJlZF91c2VybmFtZSI6InBvcnRhbGFkbWluIiwiZ2l2ZW5fbmFtZSI6IlBvcnRhbCIsImZhbWlseV9uYW1lIjoiQWRtaW4iLCJlbWFpbCI6InBvcnRhbGFkbWluQG5va2lhLmNvbSJ9.PVUkxuiXkSrKslCh88kne_t8hLqYBl3ROa50ztRuijM72r8LJIJa_Gaa431I8b3jjCibcMuBI2vW-d0yC8dhOqOWynF18gJ_TqFQnbjIYTi2EwmTonsOabAFgMZFSU1DUGsyppRm-qmhyHSta3otLho44nNylWm6q0nTRy5B8KZezBL11HTWmXFY8XsgKFnrwW3-eEM8lstpD43QW6Vz2zB0y3LKu3hwY25E-1-ExqTXnlkYduYy3zUIXrs03K2UULauUvsBotU-Y8Nid7gOmFd2jVnZupjEzLSRJA_i7MsHN-u8jWC4Q0QvLm-EU6_tBX93-DzHgjfmuYGzZEK4_A"

krb:
  requests:
    cpu: 0.05
    memory: 5Mi
  limits:
    cpu: 0.1
    memory: 50Mi

resources:
  requests:
    cpu: 0.5
    memory: 2Gi
  limits:
    cpu: 1
    memory: 8Gi

jvm:
  options: -XX:MinRAMPercentage=60.0 -XX:MaxRAMPercentage=80.0
  appOptions: -Dcom.mchange.v2.log.MLog=com.mchange.v2.log.FallbackMLog -Dcom.mchange.v2.log.FallbackMLog.DEFAULT_CUTOFF_LEVEL=WARNING

health:
  fullOutageInterval: 60
  folderModificationThreshold: 15
  hiveHdfsErrorList: "Could not open client transport,UndeclaredThrowableException,Connection refused"