{{- if .Values.rbac.enabled }}
{{- if .Values.rbac.create }}
{{- $defaultServiceAccount := include "schedulerengine.fullname" . }}
{{- $serviceAccount := .Values.rbac.serviceAccount | default $defaultServiceAccount -}}

apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ $serviceAccount }}
  namespace: {{ .Release.Namespace }}
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ template "schedulerengine.fullname" . }}
rules:
- apiGroups:
   - '*'
  resources:
  - '*'
  verbs:
  - '*'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ template "schedulerengine.fullname" . }}
  namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ template "schedulerengine.fullname" . }}
subjects:
- kind: ServiceAccount
  name: {{ $serviceAccount }}
  namespace: {{ .Release.Namespace }}
{{- end }}
{{- end }}
