kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ template "dqhi.fullname" . }}-pvc
  labels:
    app: {{ template "dqhi.name" . }}
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
  annotations:
  {{- if .Values.persistence.storageClass }}
    volume.beta.kubernetes.io/storage-class: {{ .Values.persistence.storageClass | default | quote }}
  {{- end }}
spec:
  accessModes:
    - {{ .Values.persistence.accessMode | quote }}
  resources:
    requests:
      storage: {{ .Values.persistence.size | quote }}
