FROM ubuntu
RUN mkdir /rijin
RUN apt-get update
RUN apt-get install -y python
ENV NGDB_HOME /opt/nsn/ngdb 
#COPY test.py $NGDB_HOME/rijin
#WORKDIR $NGDB_HOME/monitoring/
#RUN mkdir -p scripts 	 python-dependencies ext-dependencies extEndPointsConfigMap output resources tools
#ENTRYPOINT [ "sh" ]
