DQHI_BASE_PATH="/opt/nsn/ngdb/data-quality-metrics/data-quality-health-index"
DQHI_PRODUCT_PATH=DQHI_BASE_PATH+"/mnt/conf/"
DQHI_CUSTOM_PATH=DQHI_PRODUCT_PATH+"custom/"
DQHI_XML_PATH=DQHI_BASE_PATH+"/mnt/output/"

# DQHI_BASE_PATH="c:/upload"
# DQHI_PRODUCT_PATH=DQHI_BASE_PATH+"/conf/"
# DQHI_CUSTOM_PATH=DQHI_PRODUCT_PATH+"/custom/"
# DQHI_XML_PATH=DQHI_BASE_PATH+"/output/"

KPI_CDE_FILE_NAME = 'KPI_CDE_MAPPING.xlsx'

DQ_RULES_AND_FIELD_DEFINITIONS_FILE = 'DQ_RULES_AND_FIELD_DEFINITIONS.xlsx'