apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: {{ template "healthmonitoring.fullname" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  name: {{ template "healthmonitoring.fullname" . }}-cad
  namespace: {{ .Release.Namespace }}
data:
    technical_metadata_export_tables: |-
      ES_%,US_%,PS_%
    operational_metadata_export_jobs: |-
      