apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/scrape: "{{ .Values.prometheus.enabled }}"
  name: {{ template "healthmonitoring.fullname" . }}
  labels:
    app: {{ template "healthmonitoring.fullname" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.httpPort }}
      protocol: TCP
      name: http
  selector:
    app: {{ template "healthmonitoring.fullname" . }}
    release: {{ .Release.Name }}
